services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: "${TARGET:-simple}"
    command: [ "chainlit", "run", "--headless", "--watch", "--host", "0.0.0.0", "app.py" ]
    depends_on:
      knowledge-graph:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - "PERSISTENCE_MODULE=${PERSISTENCE_MODULE:-eventsourcing.sqlite}"
      - "SQLITE_DBNAME=/opt/data/event_store.sqlite"
      - "NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}"
      - "NEO4J_PASSWORD=${NEO4J_PASSWORD:-supersecret}"
      - "NEO4J_CONNECTION_URI=bolt://knowledge-graph:7687"
      - "NEO4J_DATABASE=movies"
      - "OLLAMA_URL=http://ollama:11434"
      - "OLLAMA_MODEL=llama3.1:8b"
      - "AGENT_TOPIC=knowledge_chat.infrastructure.domain.service.langchain_kshot_response_agent:LangchainKShotResponseAgent"
    image: movies-chat:${TARGET:-simple}
    ports:
      - "8000:8000"
    volumes:
      - "./${TARGET:-simple}:/opt/chat"
      - "./data:/opt/data"

  knowledge-graph:
    environment:
      - "NEO4J_AUTH=${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-supersecret}"
      - "NEO4J_PLUGINS=[\"apoc\"]"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--no-verbose", "localhost:7474/" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    image: graphstack/dozerdb:5.24.2
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./graph:/data"
      - "./scripts:/opt/scripts"

  ollama:
    healthcheck:
      test: [ "CMD", "ollama", "ps" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - "./ollama:/root/.ollama"
    # Uncomment the following section if you have an NVIDIA GPU configured with Docker.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
